export const demoData = {
  "Financial Data": [
    {
      "Date": "2026-01-23",
      "Financial Nature": "Frass",
      "Account Type": "Viridion",
      "Category": "Groceries",
      "Payment Method": null,
      "Project": "OECS PEARL",
      "Amount": 500,
      "Month": "January",
      "EXPENSES": 800,
      "INCOME": 1000,
      "SAVINGS": 650,
      "FRASS": 500,
      "DEBT": 200,
      "EMERGENCY FUND": 900
    },
    {
      "Date": "2026-01-15",
      "Financial Nature": "Expense",
      "Account Type": "Viridion",
      "Category": "Transportation",
      "Payment Method": null,
      "Project": null,
      "Amount": 600,
      "Month": "February",
      "EXPENSES": 1,
      "INCOME": 800,
      "SAVINGS": 1,
      "FRASS": 1,
      "DEBT": 1,
      "EMERGENCY FUND": null
    },
    {
      "Date": "2026-01-09",
      "Financial Nature": "Income",
      "Account Type": "Viridion",
      "Category": "Eating Out",
      "Payment Method": null,
      "Project": null,
      "Amount": 7000,
      "Month": "March",
      "EXPENSES": 1,
      "INCOME": 200,
      "SAVINGS": 1,
      "FRASS": 1,
      "DEBT": 1,
      "EMERGENCY FUND": null
    },
    {
      "Date": "2025-12-24",
      "Financial Nature": "Debt",
      "Account Type": null,
      "Category": null,
      "Payment Method": null,
      "Project": null,
      "Amount": 2,
      "Month": "April",
      "EXPENSES": 1,
      "INCOME": 1500,
      "SAVINGS": 20,
      "FRASS": 1,
      "DEBT": 10,
      "EMERGENCY FUND": null
    },
    {
      "Date": "2026-01-18",
      "Financial Nature": "Emergency Fund",
      "Account Type": null,
      "Category": null,
      "Payment Method": "Debit Card",
      "Project": null,
      "Amount": 200,
      "Month": "May",
      "EXPENSES": 1,
      "INCOME": 1,
      "SAVINGS": 1,
      "FRASS": 1,
      "DEBT": 1,
      "EMERGENCY FUND": null
    },
    {
      "Date": "2026-01-21",
      "Financial Nature": "Savings",
      "Account Type": null,
      "Category": null,
      "Payment Method": null,
      "Project": null,
      "Amount": 650,
      "Month": "June",
      "EXPENSES": 1,
      "INCOME": 1,
      "SAVINGS": 1,
      "FRASS": 1,
      "DEBT": 1,
      "EMERGENCY FUND": null
    },
    {
      "Date": "2026-01-21",
      "Financial Nature": "Expense",
      "Account Type": null,
      "Category": "Utilities",
      "Payment Method": null,
      "Project": null,
      "Amount": 200,
      "Month": "July",
      "EXPENSES": 1,
      "INCOME": 1,
      "SAVINGS": 1,
      "FRASS": 1,
      "DEBT": 1,
      "EMERGENCY FUND": null
    },
    {
      "Date": "2026-01-16",
      "Financial Nature": "Emergency Fund",
      "Account Type": null,
      "Category": null,
      "Payment Method": "Debit Card",
      "Project": null,
      "Amount": 41,
      "Month": "August",
      "EXPENSES": 1,
      "INCOME": 1,
      "SAVINGS": 1,
      "FRASS": 1,
      "DEBT": 1,
      "EMERGENCY FUND": null
    },
    {
      "Date": null,
      "Financial Nature": null,
      "Account Type": null,
      "Category": null,
      "Payment Method": null,
      "Project": null,
      "Amount": null,
      "Month": "September",
      "EXPENSES": 1,
      "INCOME": 1,
      "SAVINGS": 1,
      "FRASS": 1,
      "DEBT": 1,
      "EMERGENCY FUND": null
    },
    {
      "Date": null,
      "Financial Nature": null,
      "Account Type": null,
      "Category": null,
      "Payment Method": null,
      "Project": null,
      "Amount": null,
      "Month": "October",
      "EXPENSES": 1,
      "INCOME": 1,
      "SAVINGS": 1,
      "FRASS": 1,
      "DEBT": 1,
      "EMERGENCY FUND": null
    },
    {
      "Date": null,
      "Financial Nature": null,
      "Account Type": null,
      "Category": null,
      "Payment Method": null,
      "Project": null,
      "Amount": null,
      "Month": "November",
      "EXPENSES": 1,
      "INCOME": 1,
      "SAVINGS": 1,
      "FRASS": 1,
      "DEBT": 1,
      "EMERGENCY FUND": null
    },
    {
      "Date": null,
      "Financial Nature": null,
      "Account Type": null,
      "Category": null,
      "Payment Method": null,
      "Project": null,
      "Amount": null,
      "Month": "December",
      "EXPENSES": 1,
      "INCOME": 1,
      "SAVINGS": 1,
      "FRASS": 1,
      "DEBT": 1,
      "EMERGENCY FUND": 500
    },
    {
      "Date": null,
      "Financial Nature": null,
      "Account Type": null,
      "Category": null,
      "Payment Method": null,
      "Project": null,
      "Amount": null,
      "Month": "Copy Values per Month into Yearly Summary (Ctrl + Shift + V)",
      "EXPENSES": null,
      "INCOME": null,
      "SAVINGS": null,
      "FRASS": null,
      "DEBT": null,
      "EMERGENCY FUND": null
    },
    {
      "Date": null,
      "Financial Nature": null,
      "Account Type": null,
      "Category": null,
      "Payment Method": null,
      "Project": null,
      "Amount": null,
      "Month": "='Finance Tracker'!$B$4",
      "EXPENSES": "=IF($L19='Finance Tracker'!$B$4,'Finance Tracker'!$J$48,\"\")",
      "INCOME": "=IF($L19='Finance Tracker'!$B$4,'Finance Tracker'!$B$16,\"\")",
      "SAVINGS": "=IF($L19='Finance Tracker'!$B$4,'Finance Tracker'!$B$27,\"\")",
      "FRASS": "=IF($L19='Finance Tracker'!$B$4,'Finance Tracker'!$B$39,\"\")",
      "DEBT": "=IF($L19='Finance Tracker'!$B$4,'Finance Tracker'!$J$58,\"\")",
      "EMERGENCY FUND": "=IF($L19='Finance Tracker'!$B$4,'Finance Tracker'!$Q$37,\"\")"
    }
  ],
  "Body & Lifestyle Tracker Data": [
    {
      "Date": "2026-01-01",
      "Week": "=ISOWEEKNUM(A5)",
      "Weekend": "=IF(WEEKDAY($A5,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": 1,
      "Gym": 1,
      "Smoking": 1,
      "Drinking": 1,
      "Skincare": 1,
      "Haircare": 1,
      "Hand & Feet Care": 1,
      "Journal": 1,
      "Notes": null,
      "Checklist": "Category"
    },
    {
      "Date": "2026-01-02",
      "Week": "=ISOWEEKNUM(A6)",
      "Weekend": "=IF(WEEKDAY($A6,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": 2,
      "Gym": 1,
      "Smoking": 1,
      "Drinking": null,
      "Skincare": null,
      "Haircare": null,
      "Hand & Feet Care": null,
      "Journal": null,
      "Notes": null,
      "Checklist": "Gym"
    },
    {
      "Date": "2026-01-03",
      "Week": "=ISOWEEKNUM(A7)",
      "Weekend": "=IF(WEEKDAY($A7,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": 1,
      "Gym": 1,
      "Smoking": 4,
      "Drinking": 1,
      "Skincare": 1,
      "Haircare": null,
      "Hand & Feet Care": 1,
      "Journal": 1,
      "Notes": null,
      "Checklist": "Hair, Hand & Feet Care"
    },
    {
      "Date": "2026-01-04",
      "Week": "=ISOWEEKNUM(A8)",
      "Weekend": "=IF(WEEKDAY($A8,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": 2,
      "Gym": null,
      "Smoking": null,
      "Drinking": 5,
      "Skincare": 2,
      "Haircare": null,
      "Hand & Feet Care": null,
      "Journal": 1,
      "Notes": null,
      "Checklist": "Skincare"
    },
    {
      "Date": "2026-01-05",
      "Week": "=ISOWEEKNUM(A9)",
      "Weekend": "=IF(WEEKDAY($A9,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": 2,
      "Gym": null,
      "Smoking": 1,
      "Drinking": 1,
      "Skincare": null,
      "Haircare": null,
      "Hand & Feet Care": null,
      "Journal": 1,
      "Notes": null,
      "Checklist": "Smoking & Drinking"
    },
    {
      "Date": "2026-01-06",
      "Week": "=ISOWEEKNUM(A10)",
      "Weekend": "=IF(WEEKDAY($A10,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": 1,
      "Gym": null,
      "Smoking": null,
      "Drinking": null,
      "Skincare": null,
      "Haircare": 1,
      "Hand & Feet Care": null,
      "Journal": null,
      "Notes": null,
      "Checklist": "Prayers & Praises"
    },
    {
      "Date": "2026-01-07",
      "Week": "=ISOWEEKNUM(A11)",
      "Weekend": "=IF(WEEKDAY($A11,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": 2,
      "Gym": null,
      "Smoking": null,
      "Drinking": null,
      "Skincare": null,
      "Haircare": null,
      "Hand & Feet Care": null,
      "Journal": null,
      "Notes": null,
      "Checklist": "Water"
    },
    {
      "Date": "2026-01-08",
      "Week": "=ISOWEEKNUM(A12)",
      "Weekend": "=IF(WEEKDAY($A12,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": 1,
      "Gym": 1,
      "Smoking": 1,
      "Drinking": 1,
      "Skincare": 1,
      "Haircare": 1,
      "Hand & Feet Care": 1,
      "Journal": 1,
      "Notes": null,
      "Checklist": null
    },
    {
      "Date": "2026-01-09",
      "Week": "=ISOWEEKNUM(A13)",
      "Weekend": "=IF(WEEKDAY($A13,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": 2,
      "Gym": 1,
      "Smoking": 1,
      "Drinking": null,
      "Skincare": null,
      "Haircare": null,
      "Hand & Feet Care": null,
      "Journal": null,
      "Notes": null,
      "Checklist": null
    },
    {
      "Date": "2026-01-10",
      "Week": "=ISOWEEKNUM(A14)",
      "Weekend": "=IF(WEEKDAY($A14,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": 1,
      "Gym": 1,
      "Smoking": 4,
      "Drinking": 1,
      "Skincare": 1,
      "Haircare": null,
      "Hand & Feet Care": 1,
      "Journal": 1,
      "Notes": null,
      "Checklist": null
    },
    {
      "Date": "2026-01-11",
      "Week": "=ISOWEEKNUM(A15)",
      "Weekend": "=IF(WEEKDAY($A15,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": 2,
      "Gym": null,
      "Smoking": null,
      "Drinking": 5,
      "Skincare": 2,
      "Haircare": null,
      "Hand & Feet Care": null,
      "Journal": 1,
      "Notes": null,
      "Checklist": null
    },
    {
      "Date": "2026-01-12",
      "Week": "=ISOWEEKNUM(A16)",
      "Weekend": "=IF(WEEKDAY($A16,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": 2,
      "Gym": null,
      "Smoking": 1,
      "Drinking": 1,
      "Skincare": null,
      "Haircare": null,
      "Hand & Feet Care": null,
      "Journal": 1,
      "Notes": null,
      "Checklist": null
    },
    {
      "Date": "2026-01-13",
      "Week": "=ISOWEEKNUM(A17)",
      "Weekend": "=IF(WEEKDAY($A17,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": 1,
      "Gym": null,
      "Smoking": null,
      "Drinking": null,
      "Skincare": null,
      "Haircare": 1,
      "Hand & Feet Care": null,
      "Journal": null,
      "Notes": null,
      "Checklist": null
    },
    {
      "Date": "2026-01-14",
      "Week": "=ISOWEEKNUM(A18)",
      "Weekend": "=IF(WEEKDAY($A18,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": 2,
      "Gym": null,
      "Smoking": null,
      "Drinking": null,
      "Skincare": null,
      "Haircare": null,
      "Hand & Feet Care": null,
      "Journal": null,
      "Notes": null,
      "Checklist": null
    },
    {
      "Date": "2026-01-15",
      "Week": "=ISOWEEKNUM(A19)",
      "Weekend": "=IF(WEEKDAY($A19,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": null,
      "Gym": null,
      "Smoking": null,
      "Drinking": null,
      "Skincare": null,
      "Haircare": null,
      "Hand & Feet Care": null,
      "Journal": null,
      "Notes": null,
      "Checklist": null
    },
    {
      "Date": "2026-01-16",
      "Week": "=ISOWEEKNUM(A20)",
      "Weekend": "=IF(WEEKDAY($A20,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": null,
      "Gym": null,
      "Smoking": null,
      "Drinking": null,
      "Skincare": null,
      "Haircare": null,
      "Hand & Feet Care": null,
      "Journal": null,
      "Notes": null,
      "Checklist": null
    },
    {
      "Date": "2026-01-17",
      "Week": "=ISOWEEKNUM(A21)",
      "Weekend": "=IF(WEEKDAY($A21,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": null,
      "Gym": null,
      "Smoking": null,
      "Drinking": null,
      "Skincare": null,
      "Haircare": null,
      "Hand & Feet Care": null,
      "Journal": null,
      "Notes": null,
      "Checklist": null
    },
    {
      "Date": "2026-01-18",
      "Week": "=ISOWEEKNUM(A22)",
      "Weekend": "=IF(WEEKDAY($A22,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": null,
      "Gym": null,
      "Smoking": null,
      "Drinking": null,
      "Skincare": null,
      "Haircare": null,
      "Hand & Feet Care": null,
      "Journal": null,
      "Notes": null,
      "Checklist": null
    },
    {
      "Date": "2026-01-19",
      "Week": "=ISOWEEKNUM(A23)",
      "Weekend": "=IF(WEEKDAY($A23,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": null,
      "Gym": null,
      "Smoking": null,
      "Drinking": null,
      "Skincare": null,
      "Haircare": null,
      "Hand & Feet Care": null,
      "Journal": null,
      "Notes": null,
      "Checklist": null
    },
    {
      "Date": "2026-01-20",
      "Week": "=ISOWEEKNUM(A24)",
      "Weekend": "=IF(WEEKDAY($A24,2)>=6,\"\u2714\",\"\")\n",
      "Prayers & Praises": null,
      "Gym": null,
      "Smoking": null,
      "Drinking": null,
      "Skincare": null,
      "Haircare": null,
      "Hand & Feet Care": null,
      "Journal": null,
      "Notes": null,
      "Checklist": null
    }
  ],
  "Skills & Progress Tracker": [
    {
      "Date": "2026-03-01",
      "Skill Area": "AI / Coding",
      "Specific Skill": "Next.js App Router",
      "Goal / Outcome": "Build workbook dashboard",
      "Current Level (1-10)": 4,
      "Target Level (1-10)": 8,
      "Hours Invested": 3,
      "Learning Resource": "Official docs",
      "Status": "In Progress",
      "Next Review Date": "2026-03-14",
      "Notes": "Focus on CRUD + charts"
    },
    {
      "Date": "2026-03-03",
      "Skill Area": "Business",
      "Specific Skill": "Budgeting & cash flow",
      "Goal / Outcome": "Track monthly spending clearly",
      "Current Level (1-10)": 5,
      "Target Level (1-10)": 9,
      "Hours Invested": 2,
      "Learning Resource": "Personal tracker",
      "Status": "Planned",
      "Next Review Date": "2026-03-20",
      "Notes": "Connect to finance dashboard"
    }
  ],
  "Work & Business Tracker": [
    {
      "Date": "2026-03-01",
      "Area": "Consulting",
      "Project / Client": "OECS Learning Hub",
      "Task / Deliverable": "Invoice + architecture update",
      "Priority": "High",
      "Status": "Completed",
      "Hours": 6,
      "Expected Income": 1400,
      "Actual Income": 1400,
      "Expense": 0,
      "Due Date": "2026-03-05",
      "Notes": "Sent February invoice"
    },
    {
      "Date": "2026-03-06",
      "Area": "Product",
      "Project / Client": "Viridion",
      "Task / Deliverable": "Prototype tracker dashboard",
      "Priority": "Critical",
      "Status": "In Progress",
      "Hours": 4,
      "Expected Income": 0,
      "Actual Income": 0,
      "Expense": 0,
      "Due Date": "2026-03-12",
      "Notes": "Use workbook as editable DB"
    }
  ],
  "Travel Tracker": [
    {
      "Trip Name": "Birthday Cruise",
      "Destination": "Caribbean",
      "Purpose": "Celebration / self-care",
      "Start Date": "2026-08-20",
      "End Date": "2026-08-24",
      "Budget": 3000,
      "Estimated Cost": 2500,
      "Actual Cost": 0,
      "Status": "Researching",
      "Booking Link / Reference": null,
      "People": 1,
      "Notes": "Solo trip, fun + relaxing"
    },
    {
      "Trip Name": "Dental Trip",
      "Destination": "Barbados",
      "Purpose": "Dental work / shopping",
      "Start Date": "2026-05-10",
      "End Date": "2026-05-14",
      "Budget": 2200,
      "Estimated Cost": 1800,
      "Actual Cost": 0,
      "Status": "Idea",
      "Booking Link / Reference": null,
      "People": 1,
      "Notes": "Compare flights + stay"
    }
  ],
  "Purchases & Wishlist": [
    {
      "Item": "Gold chain",
      "Category": "Style",
      "Priority": "Medium",
      "Need or Want": "Want",
      "Target Budget": 2500,
      "Expected Price": 2200,
      "Actual Price": 0,
      "Purchase Status": "Researching",
      "Shop / Source": "Local jeweler",
      "Target Date": "2026-06-01",
      "Bought Date": null,
      "Notes": "Ask per gram + purity"
    },
    {
      "Item": "Bed frame",
      "Category": "Home",
      "Priority": "High",
      "Need or Want": "Need",
      "Target Budget": 1800,
      "Expected Price": 1500,
      "Actual Price": 0,
      "Purchase Status": "Planned",
      "Shop / Source": "Furniture store",
      "Target Date": "2026-04-15",
      "Bought Date": null,
      "Notes": "Basic furnishing priority"
    }
  ]
};
